spring.application.name=backend
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=TRACE
logging.level.com.arttrident.backend=TRACE

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/arttrident
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Default Server Port
server.port=8080

# JWT Configuration (Generated via Keys.secretKeyFor(SignatureAlgorithm.HS256))
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000

# File Upload Constraints
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cloudinary Configuration (Read from local environment variables)
cloudinary.cloud-name=dagggmxd0
cloudinary.api-key=344491292628769
cloudinary.api-secret=1MIf9j72UmBQRQoewUaWF8l1bwA
